# Generated by Django 2.0 on 2017-12-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
    ]
