# Generated by Django 2.0 on 2017-12-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericviews', '0005_auto_20171210_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
